services:
  therouter:
    build:
      context: ./routerDocker
      dockerfile: router.Dockerfile
    container_name: bitrouter    
    networks:
      servers:
        ipv4_address: 192.168.44.254  
      clients:
        ipv4_address: 192.168.43.254
    command: tail -f /dev/null
    
  thebitclient:
    depends_on:
      - therouter
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: bitclient
    
    cap_add:
      - NET_ADMIN
    networks:
      - clients
    command: sh clientRouteSetup.sh
  
  thebitserver:
    depends_on:
    - therouter
    build:
      context: .
      dockerfile: server.Dockerfile  
    container_name: bitserver
    cap_add:
      - NET_ADMIN
    networks:
      - servers
    command: sh serverRouteSetup.sh

networks:
  servers:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.44.0/24  
  clients:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.43.0/24